# .github/actions/shared-action/action.yml
name: Setup
description: Shared logic for workflows
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '21'
    - uses: antoniovazquezblanco/setup-ghidra@v2.0.4

    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip setuptools wheel

    - name: Install apt dependencies
      shell: bash
      run: sudo apt-get install -y pkg-config libsentencepiece-dev libprotobuf-dev

    - name: Install dependencies
      shell: bash
      run: pip install -r requirements.txt

    - name: Download Ghidrathon
      uses: robinraju/release-downloader@v1
      with:
        # The source repository path.
        # Expected format {owner}/{repo}
        # Default: ${{ github.repository }}
          repository: mandiant/Ghidrathon
          tag: v4.0.0
          fileName: '*.zip'

    - name: Install Ghidrathon
      shell: bash
      run: |
        mkdir ghidrathon-tmp
        unzip Ghidrathon*.zip -d ghidrathon-tmp
        pip install -r ghidrathon-tmp/requirements.txt
        python ghidrathon-tmp/ghidrathon_configure.py $GHIDRA_INSTALL_DIR
        unzip ghidrathon-tmp/Ghidrathon*.zip -d $GHIDRA_INSTALL_DIR/Ghidra/Extensions
        #$GHIDRA_INSTALL_DIR/support/analyzeHeadless projects TmpProject -import /bin/ls
    
    - name: Make projects directory
      shell: bash
      run: mkdir -p projects

